export const dataset = {
  nodes: [
    {
      id: 0,
      x: 16,
      y: 104,
      connections: 2,
      color: "#000",
      fillOpacity: 0.6000000000000001,
      hasStroke: false,
    },
    {
      id: 1,
      x: 621,
      y: 574,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 2,
      x: 849,
      y: 721,
      connections: 4,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 3,
      x: 871,
      y: 516,
      connections: 7,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 4,
      x: 269,
      y: 1004,
      connections: 6,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 5,
      x: 727,
      y: 276,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 6,
      x: 66,
      y: 951,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 7,
      x: 391,
      y: 82,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 8,
      x: 387,
      y: 1193,
      connections: 7,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 9,
      x: 760,
      y: 200,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 10,
      x: 563,
      y: 766,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 11,
      x: 116,
      y: 958,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 12,
      x: 369,
      y: 733,
      connections: 6,
      color: "#000",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 13,
      x: 383,
      y: 785,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 14,
      x: 613,
      y: 282,
      connections: 8,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 15,
      x: 115,
      y: 79,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 16,
      x: 198,
      y: 240,
      connections: 7,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 17,
      x: 479,
      y: 763,
      connections: 6,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 18,
      x: 438,
      y: 977,
      connections: 7,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 19,
      x: 462,
      y: 455,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 20,
      x: 481,
      y: 205,
      connections: 5,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 21,
      x: 480,
      y: 500,
      connections: 8,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 22,
      x: 478,
      y: 386,
      connections: 5,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 23,
      x: 470,
      y: 186,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 24,
      x: 77,
      y: 977,
      connections: 3,
      color: "#000",
      fillOpacity: 0.8,
      hasStroke: false,
    },
    {
      id: 25,
      x: 831,
      y: 196,
      connections: 9,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 26,
      x: 661,
      y: 22,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 27,
      x: 758,
      y: 574,
      connections: 6,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 28,
      x: 589,
      y: 681,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 29,
      x: 413,
      y: 233,
      connections: 7,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 30,
      x: 307,
      y: 1159,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 31,
      x: 383,
      y: 412,
      connections: 6,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 32,
      x: 748,
      y: 392,
      connections: 5,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 33,
      x: 749,
      y: 1105,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 34,
      x: 854,
      y: 37,
      connections: 3,
      color: "#920C00",
      fillOpacity: 0.8,
      hasStroke: false,
    },
    {
      id: 35,
      x: 602,
      y: 320,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 36,
      x: 217,
      y: 930,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 37,
      x: 540,
      y: 1106,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 38,
      x: 389,
      y: 543,
      connections: 9,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 39,
      x: 578,
      y: 300,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 40,
      x: 791,
      y: 451,
      connections: 5,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 41,
      x: 548,
      y: 288,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 42,
      x: 488,
      y: 685,
      connections: 8,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 43,
      x: 317,
      y: 29,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 44,
      x: 479,
      y: 436,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 45,
      x: 469,
      y: 483,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 46,
      x: 613,
      y: 1102,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 47,
      x: 790,
      y: 841,
      connections: 6,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 48,
      x: 83,
      y: 217,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 49,
      x: 663,
      y: 696,
      connections: 8,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 50,
      x: 576,
      y: 593,
      connections: 4,
      color: "#000",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 51,
      x: 765,
      y: 920,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 52,
      x: 725,
      y: 293,
      connections: 5,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 53,
      x: 810,
      y: 28,
      connections: 4,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 54,
      x: 549,
      y: 420,
      connections: 8,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 55,
      x: 636,
      y: 396,
      connections: 5,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 56,
      x: 206,
      y: 1122,
      connections: 5,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 57,
      x: 788,
      y: 693,
      connections: 5,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 58,
      x: 625,
      y: 883,
      connections: 8,
      color: "#000",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 59,
      x: 582,
      y: 613,
      connections: 5,
      color: "#000",
      fillOpacity: 1,
      hasStroke: true,
    },
    {
      id: 60,
      x: 654,
      y: 507,
      connections: 7,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 61,
      x: 589,
      y: 32,
      connections: 7,
      color: "#000792",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 62,
      x: 734,
      y: 338,
      connections: 5,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
    {
      id: 63,
      x: 874,
      y: 1129,
      connections: 6,
      color: "#920C00",
      fillOpacity: 1,
      hasStroke: false,
    },
  ],
  links: [
    {
      source: 21,
      target: 38,
      opacity: 0.1,
    },
    {
      source: 21,
      target: 45,
      opacity: 0.04,
    },
    {
      source: 38,
      target: 45,
      opacity: 0.1,
    },
    {
      source: 19,
      target: 44,
      opacity: 0.04,
    },
    {
      source: 19,
      target: 45,
      opacity: 0.04,
    },
    {
      source: 44,
      target: 45,
      opacity: 0.04,
    },
    {
      source: 19,
      target: 38,
      opacity: 0.04,
    },
    {
      source: 21,
      target: 44,
      opacity: 0.1,
    },
    {
      source: 31,
      target: 44,
      opacity: 0.04,
    },
    {
      source: 19,
      target: 31,
      opacity: 0.04,
    },
    {
      source: 31,
      target: 38,
      opacity: 0.1,
    },
    {
      source: 22,
      target: 44,
      opacity: 0.04,
    },
    {
      source: 22,
      target: 31,
      opacity: 0.04,
    },
    {
      source: 21,
      target: 54,
      opacity: 0.04,
    },
    {
      source: 44,
      target: 54,
      opacity: 0.1,
    },
    {
      source: 22,
      target: 54,
      opacity: 0.04,
    },
    {
      source: 42,
      target: 50,
      opacity: 0.1,
    },
    {
      source: 21,
      target: 50,
      opacity: 0.1,
    },
    {
      source: 21,
      target: 42,
      opacity: 0.04,
    },
    {
      source: 21,
      target: 60,
      opacity: 0.04,
    },
    {
      source: 54,
      target: 60,
      opacity: 0.04,
    },
    {
      source: 38,
      target: 42,
      opacity: 0.1,
    },
    {
      source: 42,
      target: 59,
      opacity: 0.1,
    },
    {
      source: 50,
      target: 59,
      opacity: 0.04,
    },
    {
      source: 1,
      target: 50,
      opacity: 0.1,
    },
    {
      source: 1,
      target: 21,
      opacity: 0.04,
    },
    {
      source: 1,
      target: 59,
      opacity: 0.04,
    },
    {
      source: 1,
      target: 60,
      opacity: 0.04,
    },
    {
      source: 12,
      target: 36,
      opacity: 0.04,
    },
    {
      source: 6,
      target: 12,
      opacity: 0.04,
    },
    {
      source: 6,
      target: 36,
      opacity: 0.04,
    },
    {
      source: 12,
      target: 38,
      opacity: 0.1,
    },
    {
      source: 12,
      target: 42,
      opacity: 0.1,
    },
    {
      source: 10,
      target: 28,
      opacity: 0.04,
    },
    {
      source: 28,
      target: 42,
      opacity: 0.04,
    },
    {
      source: 10,
      target: 42,
      opacity: 0.04,
    },
    {
      source: 28,
      target: 59,
      opacity: 0.04,
    },
    {
      source: 49,
      target: 59,
      opacity: 0.04,
    },
    {
      source: 1,
      target: 49,
      opacity: 0.04,
    },
    {
      source: 1,
      target: 27,
      opacity: 0.1,
    },
    {
      source: 27,
      target: 60,
      opacity: 0.1,
    },
    {
      source: 55,
      target: 60,
      opacity: 0.04,
    },
    {
      source: 54,
      target: 55,
      opacity: 0.04,
    },
    {
      source: 41,
      target: 54,
      opacity: 0.04,
    },
    {
      source: 22,
      target: 41,
      opacity: 0.1,
    },
    {
      source: 12,
      target: 17,
      opacity: 0.04,
    },
    {
      source: 17,
      target: 42,
      opacity: 0.04,
    },
    {
      source: 39,
      target: 41,
      opacity: 0.04,
    },
    {
      source: 39,
      target: 54,
      opacity: 0.1,
    },
    {
      source: 22,
      target: 29,
      opacity: 0.1,
    },
    {
      source: 29,
      target: 31,
      opacity: 0.04,
    },
    {
      source: 35,
      target: 55,
      opacity: 0.04,
    },
    {
      source: 35,
      target: 54,
      opacity: 0.1,
    },
    {
      source: 35,
      target: 39,
      opacity: 0.1,
    },
    {
      source: 12,
      target: 13,
      opacity: 0.04,
    },
    {
      source: 13,
      target: 17,
      opacity: 0.1,
    },
    {
      source: 10,
      target: 58,
      opacity: 0.04,
    },
    {
      source: 10,
      target: 17,
      opacity: 0.1,
    },
    {
      source: 17,
      target: 58,
      opacity: 0.1,
    },
    {
      source: 28,
      target: 49,
      opacity: 0.04,
    },
    {
      source: 29,
      target: 41,
      opacity: 0.1,
    },
    {
      source: 20,
      target: 29,
      opacity: 0.04,
    },
    {
      source: 20,
      target: 41,
      opacity: 0.1,
    },
    {
      source: 10,
      target: 49,
      opacity: 0.1,
    },
    {
      source: 14,
      target: 35,
      opacity: 0.1,
    },
    {
      source: 14,
      target: 39,
      opacity: 0.1,
    },
    {
      source: 14,
      target: 41,
      opacity: 0.1,
    },
    {
      source: 14,
      target: 52,
      opacity: 0.04,
    },
    {
      source: 35,
      target: 52,
      opacity: 0.04,
    },
    {
      source: 14,
      target: 20,
      opacity: 0.1,
    },
    {
      source: 27,
      target: 49,
      opacity: 0.1,
    },
    {
      source: 32,
      target: 60,
      opacity: 0.1,
    },
    {
      source: 32,
      target: 55,
      opacity: 0.1,
    },
    {
      source: 55,
      target: 62,
      opacity: 0.1,
    },
    {
      source: 35,
      target: 62,
      opacity: 0.04,
    },
    {
      source: 23,
      target: 61,
      opacity: 0.1,
    },
    {
      source: 20,
      target: 23,
      opacity: 0.04,
    },
    {
      source: 20,
      target: 61,
      opacity: 0.04,
    },
    {
      source: 23,
      target: 29,
      opacity: 0.04,
    },
    {
      source: 32,
      target: 40,
      opacity: 0.1,
    },
    {
      source: 40,
      target: 60,
      opacity: 0.04,
    },
    {
      source: 32,
      target: 62,
      opacity: 0.1,
    },
    {
      source: 14,
      target: 61,
      opacity: 0.1,
    },
    {
      source: 27,
      target: 40,
      opacity: 0.04,
    },
    {
      source: 25,
      target: 32,
      opacity: 0.1,
    },
    {
      source: 25,
      target: 62,
      opacity: 0.1,
    },
    {
      source: 7,
      target: 16,
      opacity: 0.1,
    },
    {
      source: 16,
      target: 29,
      opacity: 0.1,
    },
    {
      source: 7,
      target: 29,
      opacity: 0.04,
    },
    {
      source: 16,
      target: 31,
      opacity: 0.04,
    },
    {
      source: 16,
      target: 38,
      opacity: 0.1,
    },
    {
      source: 13,
      target: 36,
      opacity: 0.1,
    },
    {
      source: 5,
      target: 52,
      opacity: 0.1,
    },
    {
      source: 25,
      target: 52,
      opacity: 0.04,
    },
    {
      source: 5,
      target: 25,
      opacity: 0.1,
    },
    {
      source: 52,
      target: 62,
      opacity: 0.1,
    },
    {
      source: 5,
      target: 9,
      opacity: 0.04,
    },
    {
      source: 9,
      target: 25,
      opacity: 0.1,
    },
    {
      source: 5,
      target: 14,
      opacity: 0.04,
    },
    {
      source: 49,
      target: 57,
      opacity: 0.1,
    },
    {
      source: 27,
      target: 57,
      opacity: 0.04,
    },
    {
      source: 3,
      target: 27,
      opacity: 0.1,
    },
    {
      source: 3,
      target: 40,
      opacity: 0.04,
    },
    {
      source: 47,
      target: 57,
      opacity: 0.04,
    },
    {
      source: 47,
      target: 49,
      opacity: 0.04,
    },
    {
      source: 18,
      target: 58,
      opacity: 0.04,
    },
    {
      source: 17,
      target: 18,
      opacity: 0.04,
    },
    {
      source: 49,
      target: 58,
      opacity: 0.1,
    },
    {
      source: 3,
      target: 57,
      opacity: 0.04,
    },
    {
      source: 7,
      target: 23,
      opacity: 0.04,
    },
    {
      source: 7,
      target: 61,
      opacity: 0.1,
    },
    {
      source: 25,
      target: 40,
      opacity: 0.04,
    },
    {
      source: 9,
      target: 14,
      opacity: 0.04,
    },
    {
      source: 13,
      target: 18,
      opacity: 0.04,
    },
    {
      source: 4,
      target: 18,
      opacity: 0.1,
    },
    {
      source: 4,
      target: 13,
      opacity: 0.04,
    },
    {
      source: 15,
      target: 48,
      opacity: 0.1,
    },
    {
      source: 16,
      target: 48,
      opacity: 0.1,
    },
    {
      source: 15,
      target: 16,
      opacity: 0.1,
    },
    {
      source: 38,
      target: 48,
      opacity: 0.04,
    },
    {
      source: 2,
      target: 47,
      opacity: 0.04,
    },
    {
      source: 2,
      target: 57,
      opacity: 0.04,
    },
    {
      source: 2,
      target: 3,
      opacity: 0.04,
    },
    {
      source: 11,
      target: 36,
      opacity: 0.1,
    },
    {
      source: 6,
      target: 11,
      opacity: 0.04,
    },
    {
      source: 47,
      target: 58,
      opacity: 0.1,
    },
    {
      source: 47,
      target: 51,
      opacity: 0.1,
    },
    {
      source: 51,
      target: 58,
      opacity: 0.1,
    },
    {
      source: 43,
      target: 61,
      opacity: 0.04,
    },
    {
      source: 7,
      target: 43,
      opacity: 0.04,
    },
    {
      source: 16,
      target: 43,
      opacity: 0.04,
    },
    {
      source: 9,
      target: 61,
      opacity: 0.1,
    },
    {
      source: 3,
      target: 25,
      opacity: 0.04,
    },
    {
      source: 9,
      target: 26,
      opacity: 0.04,
    },
    {
      source: 26,
      target: 61,
      opacity: 0.04,
    },
    {
      source: 4,
      target: 36,
      opacity: 0.1,
    },
    {
      source: 46,
      target: 51,
      opacity: 0.1,
    },
    {
      source: 46,
      target: 58,
      opacity: 0.04,
    },
    {
      source: 47,
      target: 63,
      opacity: 0.04,
    },
    {
      source: 2,
      target: 63,
      opacity: 0.1,
    },
    {
      source: 6,
      target: 38,
      opacity: 0.1,
    },
    {
      source: 4,
      target: 11,
      opacity: 0.1,
    },
    {
      source: 15,
      target: 43,
      opacity: 0.04,
    },
    {
      source: 26,
      target: 53,
      opacity: 0.04,
    },
    {
      source: 9,
      target: 53,
      opacity: 0.1,
    },
    {
      source: 26,
      target: 43,
      opacity: 0.1,
    },
    {
      source: 11,
      target: 56,
      opacity: 0.1,
    },
    {
      source: 4,
      target: 56,
      opacity: 0.1,
    },
    {
      source: 6,
      target: 24,
      opacity: 0.04,
    },
    {
      source: 11,
      target: 24,
      opacity: 0.1,
    },
    {
      source: 0,
      target: 15,
      opacity: 0.04,
    },
    {
      source: 0,
      target: 48,
      opacity: 0.1,
    },
    {
      source: 8,
      target: 37,
      opacity: 0.1,
    },
    {
      source: 18,
      target: 37,
      opacity: 0.1,
    },
    {
      source: 8,
      target: 18,
      opacity: 0.04,
    },
    {
      source: 37,
      target: 58,
      opacity: 0.04,
    },
    {
      source: 18,
      target: 30,
      opacity: 0.1,
    },
    {
      source: 4,
      target: 30,
      opacity: 0.1,
    },
    {
      source: 37,
      target: 46,
      opacity: 0.04,
    },
    {
      source: 25,
      target: 53,
      opacity: 0.1,
    },
    {
      source: 25,
      target: 34,
      opacity: 0.04,
    },
    {
      source: 34,
      target: 53,
      opacity: 0.1,
    },
    {
      source: 3,
      target: 34,
      opacity: 0.1,
    },
    {
      source: 24,
      target: 56,
      opacity: 0.04,
    },
    {
      source: 30,
      target: 56,
      opacity: 0.04,
    },
    {
      source: 8,
      target: 46,
      opacity: 0.04,
    },
    {
      source: 8,
      target: 33,
      opacity: 0.04,
    },
    {
      source: 33,
      target: 46,
      opacity: 0.04,
    },
    {
      source: 33,
      target: 51,
      opacity: 0.1,
    },
    {
      source: 51,
      target: 63,
      opacity: 0.04,
    },
    {
      source: 8,
      target: 56,
      opacity: 0.04,
    },
    {
      source: 8,
      target: 30,
      opacity: 0.04,
    },
    {
      source: 8,
      target: 63,
      opacity: 0.04,
    },
    {
      source: 33,
      target: 63,
      opacity: 0.1,
    },
    {
      source: 3,
      target: 63,
      opacity: 0.1,
    },
  ],
};
